### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by cvrebert** [kurisubrooks/caramel#14]
Which browsers and versions thereof does Caramel aim to support? The docs don't currently seem to state this anywhere.

**Comment by kurisubrooks** [comment]
Oh darn, that didn’t even cross my mind to include that in the docs.


I’ll include it once I get a chance to properly test it :3




But for now, as a vague answer: Anything that supports CSS3 will work with Caramel.


—
Kurisu Brookshttp://kurisubrooks.com/

**Comment by Penagwin** [comment]
It is being tested on Firefox, and Google Chrome. Anything that is not based on those,  may be hit or miss.

**Comment by kurisubrooks** [comment]
I think he meant what version of what browser is minimum. 
Something like Internet Explorer 8, Chrome 23, Firefox 8 or whatever

**Comment by kurisubrooks** [comment]
Added to README.md on Master
