### ISSUE TITLE
<button>s and <a>-buttons are different sizes

### ISSUE THREAD

**Issue by cvrebert** [kurisubrooks/caramel#16]
Admittedly, there are no examples of `<button>`s in the docs (a minor oversight perhaps?), but it seems like a proper framework ought to support them, and the `btn` class does work on them, except that they're smaller than the other btns.

For example, in:
```html
<a class="btn success">Anchor</a>
<button class="btn success">Button</button>
<input type="submit" class="btn success" value="Input">
```
the `<button>` is noticeably shorter than the `<a>` and the `<input>`.

Environment: Chrome 41 on OS X Yosemite

**Comment by kurisubrooks** [comment]
I'll look into this, thanks

**Comment by kurisubrooks** [comment]
Fixed in dev branch
