### ISSUE TITLE
Fixed-position navigations?

### ISSUE THREAD

**Issue by cvrebert** [kurisubrooks/caramel#17]
Would you consider supporting Navigations fixed to the top or bottom of the viewport?

**Comment by kurisubrooks** [comment]
@whoiskenjackson - Wanna take care of this one?

**Comment by kurisubrooks** [comment]
Sure. I'll let you know when I figure it out :) @whoiskenjackson

**Comment by whoiskenjackson** [comment]
This is something we can accomplish. Probably not the bottom of the viewport, but definitely the top.

**Comment by kurisubrooks** [comment]
Completed. Pull #24
https://github.com/kurisubrooks/caramel/pull/24
