### ISSUE TITLE
Right-aligned Navbar

### ISSUE THREAD

**Issue by KazukiKF** [kurisubrooks/caramel#22]
When using class="right" inside a navbar, they disappear below the navar (and show on mouseover) when the window/screen is small enough (like on a phone). If you resize the window bigger, the stay hidden.

![screenshot_4](https://cloud.githubusercontent.com/assets/5019279/6746516/8ac76b10-cf1d-11e4-9f13-682e03dc0dab.png)
![screenshot_5](https://cloud.githubusercontent.com/assets/5019279/6746517/8ac8143e-cf1d-11e4-8ee3-46ae12a2e252.png)
![screenshot_6](https://cloud.githubusercontent.com/assets/5019279/6746518/8ad056c6-cf1d-11e4-88cb-8ed267f540c7.png)

**Comment by kurisubrooks** [comment]
@whoiskenjackson — Javascript ain't my thing, would this be possible for you to do?

**Comment by whoiskenjackson** [comment]
Absolutely. I'll take a look!

**Comment by kurisubrooks** [comment]
Fixed. https://github.com/kurisubrooks/caramel/pull/24
