### ISSUE TITLE
navbar right aligned dropdown overflow

### ISSUE THREAD

**Issue by kurisubrooks** [kurisubrooks/caramel#25]
Dropdown menu items overflow if on the right side.

@whoiskenjackson — maybe if it's in .right, make the dropdown to the left of the button underneath, rather than being on the right. possible?

![http://kurisubrooks.com/img/2015-03-22_0425.png](http://kurisubrooks.com/img/2015-03-22_0425.png)

**Comment by kurisubrooks** [comment]
![http://kurisubrooks.com/img/2015-03-22_0425.png](http://kurisubrooks.com/img/2015-03-22_0425.png)

**Comment by whoiskenjackson** [comment]
I think this is possible. I can package this in with the other fixes (simplifying css).

**Comment by kurisubrooks** [comment]
Fixed in Caramel 1.3
