### ISSUE TITLE
logo.xml

### ISSUE THREAD

**Issue by Penagwin** [kurisubrooks/caramel#30]
Should be logo.svg .

It is an svg file, valid xml yes, butnot the correct extensions. icon.svg is already svg.

**Comment by kurisubrooks** [comment]
logo.svg is the actual svg file, whereas logo.xml is just a way for me to have it's xml code, so I can use it in HTML at a later date.

**Comment by kurisubrooks** [comment]
Removed in Release 1.5

**Comment by scottstamp** [comment]
@Penagwin actually is correct in the semantics of this issue. .SVG and .XML are equivalent formats, just handled with a different MIME type by the web server. If you need a file to reference, use the .SVG and just open it as a text editor.
