### ISSUE TITLE
Add styles for more form controls

### ISSUE THREAD

**Issue by erikthered** [kurisubrooks/caramel#36]
It doesn't look like radio buttons, checkboxes or selects are currently styled. Would it be feasible to add these?

**Comment by kurisubrooks** [comment]
I've been trying to do this for a while, but I still don't know how.. Sorry to disappoint, but when I figure it out, they'll be included :smile:

**Comment by gratimax** [comment]
Honestly there's not much to do in terms of checkboxes, most of their behavior is hidden in the shadow DOM. If you want to style them, most times you'd need to create your own checkboxes. For example, [bootstrap](https://github.com/twbs/bootstrap/blob/master/less/forms.less) does almost nothing with regards to actually styling checkboxes/radio buttons other than positioning.

**Comment by erikthered** [comment]
I was mostly concerned with selects, I thought I'd just lump in any other form controls that weren't covered.

**Comment by kurisubrooks** [comment]
Well form what i'm searching, I don't think it's possible to do much with them. Sorry

**Comment by whoiskenjackson** [comment]
Selects are probably the hardest and most inconsistent thing to style. So if you're worried about older browsers you may be in for a world of hurt. However, you'll have an easier time styling with newer browsers.

BUT, good news is that I've been down this painful road a lot recently. I'd check out this:

http://wtfforms.com/

Also, I'm working on something myself that is a spin-off of that, but it's definitely not ready for primetime, but you can take a look if you'd like:

https://github.com/harlem-digital/wicked-forms
