### ISSUE TITLE
Dropdown Closing Behavior

### ISSUE THREAD

**Issue by KazukiKF** [kurisubrooks/caramel#39]
If I click somewhere else on the page all dropdowns stay open, whereas I expected them to close.

![image](https://cloud.githubusercontent.com/assets/5019279/8762539/9c32c93e-2dbf-11e5-809d-8209e5d7d4ec.png)

**Comment by kurisubrooks** [comment]
@whoiskenjackson

**Comment by kurisubrooks** [comment]
GitHub auto closed this when I pulled into Master.
